#!/usr/bin/env python3
from modules import nxfconfigBuilder, nfconfigBuilder
from colorama import Fore, Style, init
import inquirer

# Initialise colorama
init(autoreset=True)

# Print start-up message
print(f"{Fore.CYAN}  ____             __ _       ____        _ _     _           ")
print(f"{Fore.CYAN} / ___|___  _ __  / _(_) __ _| __ ) _   _(_) | __| | ___ _ __ ")
print(f"{Fore.CYAN}| |   / _ \| '_ \| |_| |/ _` |  _ \| | | | | |/ _` |/ _ \ '__|")
print(f"{Fore.CYAN}| |__| (_) | | | |  _| | (_| | |_) | |_| | | | (_| |  __/ |   ")
print(f"{Fore.CYAN} \____\___/|_| |_|_| |_|\__, |____/ \__,_|_|_|\__,_|\___|_|   ")
print(f"{Fore.CYAN}                        |___/                                 ")

print(f"""
{Fore.MAGENTA}This tool helps you to build a custom Nextflow config file for your HPC 
based on your specified job scheduler and resources. Follow the prompts 
to specify your settings.
""")

# Prompt user for desired action 
config_type_question = [
  inquirer.List('config_type',
                message="What type of configuration would you like to build?",
                choices=['custom', 'nfcore'],
            ),
]
answers = inquirer.prompt(config_type_question)
config_type = answers['config_type']

if config_type == "custom":
    nxfconfigBuilder()
elif config_type == "nfcore":
    nfconfigBuilder()
else:
    print(f"{Fore.RED}Invalid selection. Please run the script again and enter either custom or nf-core.\n" + Style.RESET_ALL)
